<style>
body {
    background-image:url(<?=$this->basePath() . '/img/33SqsHx.jpg'?>);
    background-size:cover
}
</style>
</br>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('httpsecurityheaders', array('action' => 'result')));
$form->prepare();
?>
<div align="center">
    <div class="input-group">
    <h3 style="color: white;">&#9658; Website&#9660;</h3>
<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
    </div>
</div>
